name: MacOS + JDK 8

on:
  schedule:
  - cron: 0 0,8,16 * * *

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install
