name: MacOS + JDK 11

on:
  schedule:
  - cron: 0 4,12,20 * * *

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn clean install
